[theme]
base = "light"
primaryColor = "#f7931a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f7"
textColor = "#111111"
font = "sans serif"

[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
